# Ejercicios Numpy
**Nombre:** Roberto Cruz Lozano.

**Expediente:** 278788

Realiza los ejecicios que se indican en este notebook para practicar tu uso de numpy

In [1]:
import numpy as np

**Ejercicios**

1.   Crea un arreglo con los siguientes valores: `10, 15, 20, 25, 30, 35, 40`










In [2]:
arr = np.arange(10, 41, 5)
arr

array([10, 15, 20, 25, 30, 35, 40])

2.   Crea un arreglo que contenga los valores: `1,4,9,6,3` en una 3da dimension





In [3]:
arr = np.array([[[1, 4, 9, 6, 3], [1, 4, 9, 6, 3], [1, 4, 9, 6, 3]]])
arr.shape

(1, 3, 5)



3.   Verifica por medio de codigo que el arreglo escrito en el ejercicio anterior corresponda a una 3ra dimension.



In [4]:
print(arr.shape)

(1, 3, 5)


4.   Accede e imprime el 5to elemento del siguiente arreglo  
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```
(Deberas crear el arreglo y ejecutarlo)



In [5]:
arreglo = np.array([1, 6, 9, 3, 4, 6, 8, 5, 10, 23, 5, 4])
print(arreglo[4])

4


5.   Como puedes imprimir el numero 23 del arreglo
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```




In [6]:
print(arreglo[-3])

23


6.   Como puedes imprimir el numero 23 del arreglo
```
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
```
(Deberas crear el arreglo y ejecutarlo)


In [7]:
arreglo = np.array([[1, 6, 9, 3, 4, 6], [8, 5, 10, 23, 5, 4]])
print(arreglo[1][-3])

23


7.   Como puedes imprimir el ultimo elemento del arreglo
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [8]:
arreglo = np.array([1, 6, 9, 3, 4, 6, 8, 5, 10, 23, 5, 4])
print(arreglo[-1])

4


8.   Genera un nuevo arreglo a partir del que se muestra, en el que incluyas los elementos de la posicion 3 (incluyendolo, hasta la posicion 9 (sin incluirla)
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [9]:
arreglo = np.array([1, 6, 9, 3, 4, 6, 8, 5, 10, 23, 5, 4])
arr = arreglo[3:9]
arr

array([ 3,  4,  6,  8,  5, 10])

9. Genera un nuevo arreglo a partir del siguiente, con cada 2do elemento del arreglo
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [10]:
arreglo = np.array([1, 6, 9, 3, 4, 6, 8, 5, 10, 23, 5, 4])
arr = arreglo[1::2]
arr

array([ 6,  3,  6,  5, 23,  4])

10. Muestra el tipo de los datos contenidos en el siguiente arreglo:


```
arreglo = np.array([6,2,3,9,4])
```



In [11]:
arreglo = np.array([6, 2, 3, 9, 4])
print(arreglo.dtype)

int32


11. Especifica desde la declaracion del arreglo que el tipo de dato para que sea String
```
arreglo = np.array([6,2,3,9,4])
```

In [12]:
arreglo = np.array([6, 2, 3, 9, 4], dtype = 'str')
arreglo

array(['6', '2', '3', '9', '4'], dtype='<U1')

12. Declara el siguiente arreglo y posteriormente indica que sea de tipo `integer`

```
arreglo = np.array([6.3,2.5,3.0,9.1,4.9])
```

In [13]:
arreglo = np.array([6.3, 2.5, 3.0, 9.1, 4.9], dtype = 'int32')
arreglo

array([6, 2, 3, 9, 4])

12. Redacta la diferencia entre copiar un arrego con el comando copy() y el comando view()
¿Que ventaja crees que tiene view()?

---
**Ambos `copy()` y `view()` se utilizan para copiar datos y luego realizar operaciones en ellos.**
- La única diferencia entre estas dos funciones es que la función `copy()` creará una matriz NumPy separada (si realiza algún cambio en esta matriz copiada, no afectará la matriz original y viceversa ). Pero, con la función `view()`, no habrá una matriz NumPy separada y si realiza algún cambio en esta nueva matriz, afectará a la matriz original y viceversa .
---

13. Indica cuantos elementos tiene el siguiente arreglo:

```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [14]:
arreglo = np.array([1, 6, 9, 3, 4, 6, 8, 5, 10, 23, 5, 4])
print(arreglo.size)

12


14. Indica cuantos elementos tiene el siguiente arreglo:
```
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
```

In [15]:
arreglo = np.array([[1, 6, 9, 3, 4, 6], [8, 5, 10, 23, 5, 4]])
print(arreglo.size)

12


14. Redimensiona el siguiente arreglo de 1-D a 2-D con 3 subarreglos y que contengan 4 elementos en cada segmento:

```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [16]:
arreglo = np.array([1, 6, 9, 3, 4, 6, 8, 5, 10, 23, 5, 4])
print(arreglo.reshape(3, 4))

[[ 1  6  9  3]
 [ 4  6  8  5]
 [10 23  5  4]]


15. Redimensiona el siguiente arreglo de 2-D a 1-D:

```
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
```

In [17]:
arreglo = np.array([[1, 6, 9, 3, 4, 6], [8, 5, 10, 23, 5, 4]])
print(arreglo.flatten())

[ 1  6  9  3  4  6  8  5 10 23  5  4]
